version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-desafio
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - '80:3000'
    volumes:
      - ./src:/app/src